name: Build and Publish image to Docker Hub

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:

  build_and_publish:

    runs-on: ubuntu-latest

    steps:
     - name: checkout
       uses: actions/checkout@v4
     - name: build image
       run: docker build ./ -t nvkhoi1807/auths-2fa-mern-be:latest
     - name: push to docker hub
       run: |
        docker login -u nvkhoi1807 -p ${{ secrets.AUTHS_2FA_MERN_DOCKER_HUB_TOKEN }}
        docker push nvkhoi1807/auths-2fa-mern-be:latest
