name: Build and Publish Image to ECR
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      version_bump:
        description: 'Version bump type (major, minor, patch)'
        required: false
        default: 'patch'

env:
  AWS_REGION: us-east-1
jobs:
  build_and_publish_to_ecr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Read Current Version
        id: current-version
        run: |
          CURRENT_VERSION=$(cat version)
          echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_OUTPUT

      - name: Increment Version
        id: new-version
        run: |
          CURRENT_VERSION="${{ steps.current-version.outputs.CURRENT_VERSION }}"
          VERSION_BUMP="${{ github.event.inputs.version_bump || 'patch' }}"

          # Split version into major, minor, patch
          IFS='.' read -r MAJOR MINOR PATCH <<< "$CURRENT_VERSION"

          # Increment based on bump type
          case $VERSION_BUMP in
            "major")
              MAJOR=$((MAJOR + 1))
              MINOR=0
              PATCH=0
              ;;
            "minor")
              MINOR=$((MINOR + 1))
              PATCH=0
              ;;
            "patch")
              PATCH=$((PATCH + 1))
              ;;
            *)
              echo "Invalid version bump type. Using patch."
              PATCH=$((PATCH + 1))
              ;;
          esac

          NEW_VERSION="$MAJOR.$MINOR.$PATCH"
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_OUTPUT
          echo "New version: $NEW_VERSION"

      - name: Build, Tag, and Push Docker Image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: auths-2fa-mern-dev-backend
          IMAGE_TAG: ${{ steps.new-version.outputs.NEW_VERSION }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

      - name: Update Version File
        env: 
          REPO_NAME: ${{ github.repository }}
        run: |
          NEW_VERSION="${{ steps.new-version.outputs.NEW_VERSION }}"
          echo "$NEW_VERSION" > version
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add version
          git commit -m "Bump version to $NEW_VERSION"
          git push https://${GITOPS_REPO_PAT}@github.com/viekoi/${REPO_NAME} HEAD:main