name: Build and Publish image to Docker Hub
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
env:
  AWS_REGION: us-east-1
  GITOPS_REPO_NAME: auths-2fa-mern-gitops
jobs:
  build_and_publish_to_ecr:
    runs-on: ubuntu-latest
    steps:
     - name: checkout
       uses: actions/checkout@v4
     - name: Configure AWS Credentials
       uses: aws-actions/configure-aws-credentials@v4
       with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: ${{ env.AWS_REGION }}
     - name: Login to Amazon ECR
       id: login-ecr
       uses: aws-actions/amazon-ecr-login@v2
     - name: Build, tag, and push docker image to Amazon ECR
       env:
         REGISTRY: ${{ steps.login-ecr.outputs.registry }}
         REPOSITORY: auths-2fa-mern-dev-backend
         IMAGE_TAG: ${{ github.sha }}
       run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
     - name: Checkout GitOps repository         
       uses: actions/checkout@v4
       with:
         repository: viekoi/${{ env.GITOPS_REPO_NAME }}
         path: gitops
         token: ${{ secrets.GITOPS_REPO_PAT }}
     - name: Update Deployment File
       working-directory: kubernetes-manifest/backend
       env:
         REGISTRY: ${{ steps.login-ecr.outputs.registry }}
         REPOSITORY: auths-2fa-mern-dev-backend
         IMAGE_TAG: ${{ github.sha }}
       run: |
         git config --global user.name "viekoi"
         git config --global user.email "vkhoi444@gmail.com"
         IMAGE_TAG="${REGISTRY}/${REPOSITORY}:${IMAGE_TAG}"
         sed -i "s|image:.*|image: ${IMAGE_TAG}|" deployment.yaml
         git add deployment.yaml
         git commit -m "Update image ${IMAGE_TAG}"
         git push
